### ISSUE TITLE
htrace is broken

### ISSUE THREAD

**Issue by andig** [djerfy/dockerfiles#2]
❯ docker run djerfy/htrace

    not found in PATH: geoiplookup jq testssl observatory ssllabs-scan mixed-content-scan nmap
    /htrace.sh-1.1.0/bin/../src/helpers: line 114: tput: command not found

**Comment by djerfy** [comment]
Thank you for you report, I see tomorrow.
Else look this => https://github.com/trimstray/htrace.sh/tree/master/build

**Comment by djerfy** [comment]
Release `1.1.7` released. Build from the official repository.
